#definir l'alphabet
#recuperer les variable
#dire d afficher l alphabet a partir de cette lettre "variable"
#afficher

a = gets.chomp


if a == "a"
    puts "abcdefghijklmnopqrstuvwxyz"
elsif a == "b"
    puts "bcdefghijklmnopqrstuvwxyz"
elsif a == "c"
    puts "cdefghijklmnopqrstuvwxyz"
elsif a == "d"
    puts "defghijklmnopqrstuvwxyz"
elsif a == "e"
    puts "efghijklmnopqrstuvwxyz"
elsif a == "f"
    puts "fghijklmnopqrstuvwxyz"
elsif a == "g"
    puts "ghijklmnopqrstuvwxyz"
elsif a == "h"
    puts "hijklmnopqrstuvwxyz"
elsif a == "i"
    puts "ijklmnopqrstuvwxyz"
elsif a == "j"
    puts "jklmnopqrstuvwxyz"
elsif a == "k"
    puts "klmnopqrstuvwxyz"
elsif a == "l"
    puts "lmnopqrstuvwxyz"
elsif a == "m"
    puts "mnopqrstuvwxyz"
elsif a == "n"
    puts "nopqrstuvwxyz"
elsif a == "o"
    puts "opqrstuvwxyz"
elsif a == "p"
    puts "pqrstuvwxyz"
elsif a == "q"
    puts "qrstuvwxyz"
elsif a == "r"
    puts "rstuvwxyz"
elsif a == "s"
    puts "stuvwxyz"
elsif a == "t"
    puts "tuvwxyz"
elsif a == "u"
    puts "uvwxyz"
elsif a == "v"
    puts "vwxyz"
elsif a == "w"
    puts "wxyz"
elsif a == "x"
    puts "xyz"
elsif a == "y"
    puts "yz"
elsif a == "z"
    puts "z"
else 
    puts "error"
end